site_name: My Note
nav:
  - Math: 
    - 高等数学A:
      - 0.Start: math/0.Start.md 
      - 4.不定积分: math/4.IndefInt.md
      - 8/10.多元函数微积分:
        - 8.1.多元函数微分: math/8.MutiValFunctionDe.md
        - 8.2.Jacobi矩阵与全微分: math/8.JacobiMartix&TotalDe.md
        - 8.3.8.Hessian矩阵与极值: math/8.HessianMartix&ExtremeVal.md
        - 10.1.Describe a Vector Feild: math/10.Describe_a_VectorFeild.md
        - 10.2.Green公式的空间形式: math/10.Green'sSpaceForm.md
      - 11.线性微分方程理论: math/11.DiffentialEquation.md
    - 离散数学:
      - Some Notes: math/DiscreteMath/SomeNotes.md
  - Computer Science:
    - Start: cs/start.md
    - C++:
      - Range Loop: cs/C++_loop.md
      - 类的构造与组合: cs/C++_C&O(1).md
      - 继承与多态: cs/C++_C&O(2).md
      - 数据的共享与保护: cs/C++_C&O(3).md
      - OperatorOverride: cs/C++_OperatorOverride.md
      - Template: cs/C++_Template.md
      - Template_git: cs/ReadMe.md
      - Namespace: cs/C++_Namespace.md
      - Exception: cs/C++_Exception.md
    - Algorithm: 
      - 伯努利方法: cs/Bernoulli's_method.md
      - 傅里叶-莫茨金消元法: cs/fourier-motzkin-elimination.md
  - Philosophy:
    - The Republic: 
      - Index: Philosophy/TheRepublic/0.md
      - Book Ⅰ: Philosophy/TheRepublic/1.md
  - Review:
    - C++: 
      - 练习01-概论: review/c++/1.md
      - 练习02-基本语法: review/c++/2.md
      - 练习03-函数: review/c++/3.md
      - 练习04-类与对象: review/c++/4.md
      - 练习05-数据的共享与保护: review/c++/5.md
      - 练习06-数组和指针: review/c++/6.md
      - 练习07-类的继承: review/c++/7.md
      - 练习08-多态性: review/c++/8.md
      - 练习09-模板: review/c++/9.md
      - 练习10-异常处理: review/c++/10.md
    - 网络工程导论: review/NetworkPreface.md
    - 创业学:
      - 题库_1: review/Creativity/1.md
      - 题库_2: review/Creativity/2.md
    - 中国近代史纲要:
      - Start: review/history/index.md
      - 附录.1.条约: review/history/1.md
      - 附录.2.Q&A: review/history/2.md
      - 附录.3.会议: review/history/3.md
      - Chapter.1: review/history/Chapter.1.md
      - Chapter.2: review/history/Chapter.2.md
      - Chapter.3: review/history/Chapter.3.md
      - Chapter.4: review/history/Chapter.4.md
      - Chapter.5: review/history/Chapter.5.md
      - Chapter.6: review/history/Chapter.6.md
      - Chapter.7: review/history/Chapter.7.md
    - 思想道德与法治: 
      - Question and Answer: review/Religion/0.md
    - 毛泽东思想和中国特色社会主义理论体系概论:
      - Problem: 
        - Q&A: review/Mao/problem/0.md
      - Summary: review/Mao/0.md
    - 习概: 
      - Q&A: review/xi.md
  - Others:
    - Start: law/index.md
    - Law: law/Examples.md
    - Presentation: law/English.md
    - Linear Algebra: math/13.md
    - Assessments: review/mvp/assessment.md              
  - Code-server: http://8.140.235.199:8080/
theme:
  name: material
  language: zh
  font:
    text: Noto Serif SC
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换至日间模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue grey # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 自动
repo_url: https://github.com/lmhhh28/lmhhh28.github.io
repo_name: 'lmhhh28'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/chart.js@4.4.8/dist/chart.umd.min.js
  - assets/javascripts/custom.js
  - assets/javascripts/chart.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - assets/stylesheets/hero-theme.css

extra:
  generator: false